let contacts = [
  {
    id: 1,
    first_name: "Rogers",
    last_name: "Gladwell",
    email: "rgladwell0@sina.com.cn",
    gender: "Agender",
    country: "Indonesia",
  },
  {
    id: 2,
    first_name: "Patti",
    last_name: "Tattam",
    email: "ptattam1@123-reg.co.uk",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 3,
    first_name: "Guenna",
    last_name: "Lum",
    email: "glum2@spotify.com",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 4,
    first_name: "Danya",
    last_name: "Rubinfeld",
    email: "drubinfeld3@yolasite.com",
    gender: "Polygender",
    country: "China",
  },
  {
    id: 5,
    first_name: "Yevette",
    last_name: "Kleine",
    email: "ykleine4@webeden.co.uk",
    gender: "Polygender",
    country: "China",
  },
  {
    id: 6,
    first_name: "Eli",
    last_name: "Izachik",
    email: "eizachik5@hc360.com",
    gender: "Genderqueer",
    country: "China",
  },
  {
    id: 7,
    first_name: "Siegfried",
    last_name: "Connop",
    email: "sconnop6@amazon.co.uk",
    gender: "Bigender",
    country: "Russia",
  },
  {
    id: 8,
    first_name: "Barbe",
    last_name: "Beaston",
    email: "bbeaston7@wordpress.com",
    gender: "Agender",
    country: "Greece",
  },
  {
    id: 9,
    first_name: "Shem",
    last_name: "McDonnell",
    email: "smcdonnell8@yandex.ru",
    gender: "Genderqueer",
    country: "China",
  },
  {
    id: 10,
    first_name: "Archie",
    last_name: "Jahndel",
    email: "ajahndel9@yelp.com",
    gender: "Male",
    country: "Cameroon",
  },
  {
    id: 11,
    first_name: "Deirdre",
    last_name: "Pietron",
    email: "dpietrona@reddit.com",
    gender: "Non-binary",
    country: "Philippines",
  },
  {
    id: 12,
    first_name: "Wanids",
    last_name: "Hugo",
    email: "whugob@webs.com",
    gender: "Genderfluid",
    country: "Indonesia",
  },
  {
    id: 13,
    first_name: "Heddie",
    last_name: "Crix",
    email: "hcrixc@dropbox.com",
    gender: "Agender",
    country: "China",
  },
  {
    id: 14,
    first_name: "Stanly",
    last_name: "O'Neary",
    email: "sonearyd@tripadvisor.com",
    gender: "Genderfluid",
    country: "Morocco",
  },
  {
    id: 15,
    first_name: "Krishna",
    last_name: "Pryce",
    email: "kprycee@tamu.edu",
    gender: "Polygender",
    country: "Jamaica",
  },
  {
    id: 16,
    first_name: "Dione",
    last_name: "Rowland",
    email: "drowlandf@pagesperso-orange.fr",
    gender: "Bigender",
    country: "Vietnam",
  },
  {
    id: 17,
    first_name: "Tanner",
    last_name: "Slorach",
    email: "tslorachg@senate.gov",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 18,
    first_name: "Candide",
    last_name: "Christou",
    email: "cchristouh@simplemachines.org",
    gender: "Agender",
    country: "Philippines",
  },
  {
    id: 19,
    first_name: "Belinda",
    last_name: "Andriveau",
    email: "bandriveaui@squidoo.com",
    gender: "Bigender",
    country: "Vietnam",
  },
  {
    id: 20,
    first_name: "Petunia",
    last_name: "Tebald",
    email: "ptebaldj@constantcontact.com",
    gender: "Bigender",
    country: "United States",
  },
];
console.table(contacts);
for (let i = 0; i <= contacts.length - 1; i++) {}
