let data = [
  {
    id: 1,
    first_name: "Lina",
    last_name: "Polle",
    email: "lpolle0@exblog.jp",
    city: "Caluquembe",
  },
  {
    id: 2,
    first_name: "Candice",
    last_name: "Collomosse",
    email: "ccollomosse1@studiopress.com",
    city: "Pasacao",
  },
  {
    id: 3,
    first_name: "Tamarra",
    last_name: "Alyukin",
    email: "talyukin2@va.gov",
    city: "Cerrito",
  },
  {
    id: 4,
    first_name: "Margarette",
    last_name: "Brimblecombe",
    email: "mbrimblecombe3@histats.com",
    city: "Pingshan",
  },
  {
    id: 5,
    first_name: "Meyer",
    last_name: "Gatch",
    email: "mgatch4@seattletimes.com",
    city: "Gradec",
  },
  {
    id: 6,
    first_name: "Marni",
    last_name: "Bowgen",
    email: "mbowgen5@ezinearticles.com",
    city: "Dongzha",
  },
  {
    id: 7,
    first_name: "Percival",
    last_name: "Tomasutti",
    email: "ptomasutti6@livejournal.com",
    city: "Radom",
  },
  {
    id: 8,
    first_name: "Filide",
    last_name: "Danbrook",
    email: "fdanbrook7@jalbum.net",
    city: "Krasnodon",
  },
  {
    id: 9,
    first_name: "Dougie",
    last_name: "Hallen",
    email: "dhallen8@nytimes.com",
    city: "Rostokino",
  },
  {
    id: 10,
    first_name: "Friederike",
    last_name: "Erswell",
    email: "ferswell9@wikimedia.org",
    city: "Curepipe",
  },
  {
    id: 11,
    first_name: "Clerkclaude",
    last_name: "Dryden",
    email: "cdrydena@chicagotribune.com",
    city: "Seattle",
  },
  {
    id: 12,
    first_name: "Irvin",
    last_name: "Tinson",
    email: "itinsonb@walmart.com",
    city: "Jamban",
  },
  {
    id: 13,
    first_name: "Stinky",
    last_name: "Golling",
    email: "sgollingc@goo.ne.jp",
    city: "Toulouse",
  },
  {
    id: 14,
    first_name: "Starla",
    last_name: "Flatley",
    email: "sflatleyd@bloglovin.com",
    city: "Babakan",
  },
  {
    id: 15,
    first_name: "Carce",
    last_name: "Corrao",
    email: "ccorraoe@fda.gov",
    city: "Kamenický Šenov",
  },
  {
    id: 16,
    first_name: "Alli",
    last_name: "Castagnasso",
    email: "acastagnassof@gravatar.com",
    city: "Ayabe",
  },
  {
    id: 17,
    first_name: "Dave",
    last_name: "Lowsely",
    email: "dlowselyg@nasa.gov",
    city: "Pappadátes",
  },
  {
    id: 18,
    first_name: "Katuscha",
    last_name: "Tobias",
    email: "ktobiash@hhs.gov",
    city: "Balky",
  },
  {
    id: 19,
    first_name: "Tisha",
    last_name: "Summerley",
    email: "tsummerleyi@amazon.co.jp",
    city: "Wan Yai",
  },
  {
    id: 20,
    first_name: "Marena",
    last_name: "Powers",
    email: "mpowersj@github.com",
    city: "Ndewel",
  },
  {
    id: 21,
    first_name: "Levi",
    last_name: "Maes",
    email: "lmaesk@friendfeed.com",
    city: "São José de Mipibu",
  },
  {
    id: 22,
    first_name: "Ester",
    last_name: "Skeath",
    email: "eskeathl@newyorker.com",
    city: "Esik",
  },
  {
    id: 23,
    first_name: "Yettie",
    last_name: "Monks",
    email: "ymonksm@buzzfeed.com",
    city: "Valença",
  },
  {
    id: 24,
    first_name: "Neilla",
    last_name: "Ordidge",
    email: "nordidgen@diigo.com",
    city: "Buka",
  },
  {
    id: 25,
    first_name: "Merline",
    last_name: "Luddy",
    email: "mluddyo@hhs.gov",
    city: "Ban Phaeo",
  },
  {
    id: 26,
    first_name: "Puff",
    last_name: "Dennitts",
    email: "pdennittsp@google.ru",
    city: "Haicheng",
  },
  {
    id: 27,
    first_name: "Vaclav",
    last_name: "Gatfield",
    email: "vgatfieldq@engadget.com",
    city: "Karis",
  },
  {
    id: 28,
    first_name: "Teddie",
    last_name: "Musterd",
    email: "tmusterdr@fc2.com",
    city: "Huancarqui",
  },
  {
    id: 29,
    first_name: "Belva",
    last_name: "Sparwell",
    email: "bsparwells@bing.com",
    city: "Caicó",
  },
  {
    id: 30,
    first_name: "Andris",
    last_name: "Perazzo",
    email: "aperazzot@hubpages.com",
    city: "Leluo",
  },
  {
    id: 31,
    first_name: "Lucho",
    last_name: "Baff",
    email: "lbaffu@moonfruit.com",
    city: "Wangpu",
  },
  {
    id: 32,
    first_name: "Grover",
    last_name: "Coolahan",
    email: "gcoolahanv@meetup.com",
    city: "Kirkuk",
  },
  {
    id: 33,
    first_name: "Anissa",
    last_name: "Pattison",
    email: "apattisonw@cbc.ca",
    city: "Yuyue",
  },
  {
    id: 34,
    first_name: "Netty",
    last_name: "Dobbing",
    email: "ndobbingx@clickbank.net",
    city: "Knivsta",
  },
  {
    id: 35,
    first_name: "Mable",
    last_name: "Wedderburn",
    email: "mwedderburny@ucla.edu",
    city: "Lichinga",
  },
  {
    id: 36,
    first_name: "Roxi",
    last_name: "Blissett",
    email: "rblissettz@cyberchimps.com",
    city: "Anticala",
  },
  {
    id: 37,
    first_name: "Bevin",
    last_name: "Martinek",
    email: "bmartinek10@cmu.edu",
    city: "Coromandel",
  },
  {
    id: 38,
    first_name: "Casandra",
    last_name: "MacHoste",
    email: "cmachoste11@upenn.edu",
    city: "Rabat",
  },
  {
    id: 39,
    first_name: "Cozmo",
    last_name: "Meads",
    email: "cmeads12@lycos.com",
    city: "Afaahiti",
  },
  {
    id: 40,
    first_name: "Lorry",
    last_name: "Lanegran",
    email: "llanegran13@umn.edu",
    city: "Weishanzhuang",
  },
  {
    id: 41,
    first_name: "Lilah",
    last_name: "Atger",
    email: "latger14@dot.gov",
    city: "Lewoluo",
  },
  {
    id: 42,
    first_name: "Loralyn",
    last_name: "Yakunikov",
    email: "lyakunikov15@si.edu",
    city: "Perpignan",
  },
  {
    id: 43,
    first_name: "Juditha",
    last_name: "Sidnall",
    email: "jsidnall16@clickbank.net",
    city: "Bodega",
  },
  {
    id: 44,
    first_name: "Stevana",
    last_name: "Snalham",
    email: "ssnalham17@jugem.jp",
    city: "Patos Fshat",
  },
  {
    id: 45,
    first_name: "Nina",
    last_name: "Gauntlett",
    email: "ngauntlett18@wisc.edu",
    city: "Stockholm",
  },
  {
    id: 46,
    first_name: "Dacie",
    last_name: "Lindhe",
    email: "dlindhe19@pbs.org",
    city: "Beisijia",
  },
  {
    id: 47,
    first_name: "Kendell",
    last_name: "Labrenz",
    email: "klabrenz1a@phpbb.com",
    city: "Bukovany",
  },
  {
    id: 48,
    first_name: "Franciska",
    last_name: "Micklewicz",
    email: "fmicklewicz1b@jugem.jp",
    city: "Río Grande",
  },
  {
    id: 49,
    first_name: "Miguel",
    last_name: "Allender",
    email: "mallender1c@ted.com",
    city: "Villa Nueva",
  },
  {
    id: 50,
    first_name: "Ulick",
    last_name: "Petican",
    email: "upetican1d@hostgator.com",
    city: "Fuyu",
  },
];
let size = [38, 40, 42];

for (obj of data) {
  console.log(obj.first_name);
}
